query findUser($userId: ID!) {
	user(id: $userId) {
		...UserFields
	}
}

fragment UserFields on User {
	id
	username
	role
}

mutation CreateMessage($input: MessageInput) {
	createMessage(input: $input) {
		id
	}
}
